### ISSUE TITLE
IPFS hash storage

### ISSUE THREAD

**Issue by MathisGD** [morpho-org/universal-rewards-distributor#40]
The optional IPFS hash is stored (in the storage).

https://github.com/morpho-org/universal-rewards-distributor/blob/095ff788db6220441ed2f1626257f64e4062bad9/src/UniversalRewardsDistributor.sol#L26

But I'm wondering if having it in the calldata and/or log isn't enough. It would 1) reduce by a lot the cost of the update, and 2) make the contract slightly simpler.

**Comment by julien-devatom** [comment]
It eases a lot the integration to have it inside of the contract. I've stored the hash independently from the root to save read costs, The root update costs a bit more, yes, but it is a measured choice. 
Moreover, with the factory model, there is only one cold update (except if you decide to not use the ipfsHash sometimes), and the gas overhead of a warm sload is ~3k.

**Comment by MathisGD** [comment]
Can you describe what's a typical integration using the ipfs root hash? It seems to me that it is only front-ends, which could use an sdk anyway. Am I wrong?

**Comment by julien-devatom** [comment]
Yes youre right, but a frontend only want the last ipfs hash. It is not possible to query a given number of logs (instead, you wan query a block range). 

So querying logs to retrieve the hash can take more and more time (if your RPC is limiting the block width to query logs), and can returns too much data (you retrieve all ipfs hash where you want only the last one).

**Comment by MathisGD** [comment]
I find it weird to use the blockchain's storage for offchain performance issues to be honest. Will not the sdk provide this data anyway ?

**Comment by julien-devatom** [comment]
This is not an offchain preformance issue, this is just because one the role of the blochchain is to store & validate data, even for offchain usage (all usages are offchain btw).

**Comment by Rubilmax** [comment]
Shall we close this?

**Comment by MathisGD** [comment]
Sorry but I keep being convinced that this is not the way we should use a blockchain. It is exactly like L2 calldata for me, you don't store them onchain like that.

>blochchain is to store

to me no, it is not the reason why you use a blockchain

**Comment by MathisGD** [comment]
the role of a blockchain is to arrive to a consensus on some state, not to make some trusted data available. The data is available here anyway because it is on IPFS. We just want a link somewhere between this data and the blockchain, and emitting an event is perfectly suited for that.

**Comment by Rubilmax** [comment]
I agree the ipfs hash could be emitted in an event alongside the root

> So querying logs to retrieve the hash can take more and more time (if your RPC is limiting the block width to query logs), and can returns too much data (you retrieve all ipfs hash where you want only the last one).

I don't get it @julien-devatom , can't we index the root and just query events filtered by the root?

**Comment by julien-devatom** [comment]
But if you have the same root with  different metadata? This is always possible yes, but not so easy. Since this is costing gas only on root update I suggest to keep it to improve contract ux

**Comment by MathisGD** [comment]
> But if you have the same root with different metadata? 

wdym

**Comment by Rubilmax** [comment]
> But if you have the same root with  different metadata? This is always possible yes, but not so easy. Since this is costing gas only on root update I suggest to keep it to improve contract ux

In this case, with the current implementation, the updater would need to update the root anyway?

**Comment by MathisGD** [comment]
we are talking about a root clash? Can't we just assume that it's impossible?

**Comment by julien-devatom** [comment]
There is no limitation; you can put whatever you want. However, to recenter the discussion, since the ipfs metadata is in the core feature of a Merkle tree (a root only does not have any sense), I suggest keeping it to ease the utilization of the URD and mitigate the gas cost with the fact that this is costing gas only on root update, not on claim.

**Comment by Rubilmax** [comment]
The last 8 messages seem to be confusing, so I'm summarizing:

1. @MathisGD suggested to emit the ipfs hash in the event instead of storing it onchain
2. @julien-devatom you said that if for some reason the owner would like to update the ipfs hash without changing the merkle root (to add metadata to the json for example), they couldn't do it
3. I'm arguing that in both designs (storing it onchain or emitting in an event), it is the case: the owner will have to update the root with the same merkle root but a different ipfs hash to store the new ipfs hash

Do you have additional questions @MathisGD ?

The stakes are:
- view function available at any block vs event that needs to be filtered by the indexed merkle root (and take the latest event)
- gas cost of storing it onchain (SSTORE)
- technical complexity? (I don't think storing a variable to storage adds any complexity, because in both designs we're emitting the ipfs hash in the event)

So in the end, storing it onchain costs additional gas but simplify offchain RPC integration. I'm in favor of keeping the ipfs hash stored onchain

**Comment by julien-devatom** [comment]
Ty for this clear recap, and I'm also in favor to store it.
