### ISSUE TITLE
Check in `forceUpdateRoot` useful? 

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/universal-rewards-distributor#5]
https://github.com/morpho-org/universal-rewards-distributor/blob/be390deac1584e043781089ab0f840a3568f6d69/src/UniversalRewardsDistributor.sol#L196

Is this check useful? The owner can `freeze` and `forceUpdateRoot`.

**Comment by julien-devatom** [comment]
It prevents mistakes since `forceUpdateRoot` should be used only in an extreme scenario where the current root is incorrect.  And it prevents also replay attacks if an owner has signed a `forceUpdateRoot`.

I agree that these considerations are not mandatory, but adding the spec "the owner can bypass the timelock only if the distribution is frozen" is not really restrictive.

**Comment by MerlinEgalite** [comment]
The replay attack argument is a little bit weird since it could apply for any function in the wild.

It's ok to keep it though for safety you're right.
